[package]
name = "dozer-app"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "dozer"
path = "src/main.rs"

[dependencies]
dozer-core = { path = "../dozer-core" }
dozer-client = { path = "../dozer-client" }
tokio.workspace = true
iced_winit = "0.14"
iced_wgpu = { version = "0.14", default-features = true }
iced_widget = { version = "0.14", features = ["wgpu"] }
winit = "0.30"
futures = { version = "0.3", features = ["thread-pool"] }
tracing.workspace = true
tracing-subscriber.workspace = true
alacritty_terminal.workspace = true
