[package]
name = "dozerd"
version = "0.3.3"
edition.workspace = true

[dependencies]
dozer-core = { path = "../dozer-core", features = ["logging"] }
anyhow.workspace = true
tokio.workspace = true
portable-pty.workspace = true
uuid.workspace = true
serde_json.workspace = true
serde.workspace = true
toml = "0.9"
base64.workspace = true
rusqlite = { version = "0.32", features = ["bundled"] }
tokio-tungstenite.workspace = true
futures-util.workspace = true
libc.workspace = true
tempfile = "3"

[dev-dependencies]
dozer-client = { path = "../dozer-client" }
uuid.workspace = true
