[package]
name = "dozerd"
version = "0.3.3"
edition.workspace = true

[dependencies]
dozer-core = { path = "../dozer-core" }
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
portable-pty.workspace = true
uuid.workspace = true
serde_json.workspace = true
serde.workspace = true
toml = "0.9"
base64.workspace = true
rusqlite = { version = "0.32", features = ["bundled"] }

[dev-dependencies]
tempfile = "3"
